### ISSUE TITLE
Clarify how to add a new item in the JSON file and the role of GUID

### ISSUE THREAD

**Issue by igorpag** [Azure/review-checklists#105]
@erjosito correct me if I'm wrong and missed any part, but there is no clear step-by-step on how to add a new element in a checklist JSON file. I remember when you explained me the role of GUID attribute, and how to generate using one of the 1,000,000 tool/script, so trivial ok, but that piece should be documented somewhere, right?

**Comment by erjosito** [comment]
Thanks for bringing this up! I moved up the contribution section in README.md, and added some more detailed instructions in CONTRIBUTING.md. Is it any better now?

**Comment by igorpag** [comment]
You rock man! Lower SLA on response than a 64 node cluster!

**Comment by erjosito** [comment]
Ha ha, I think that means we can close this one. Thanks again for the feedback, keep it coming!

**Comment by julie-ng** [comment]
@erjosito related to this, is the JSON schema documented anywhere? It would be better if it was closest to the JSON file itself.

I'm looking for something like this
https://github.com/adobe/jsonschema2md/blob/main/examples/docs/abstract-definitions-first.md

**Comment by erjosito** [comment]
Good point! Would you be so kind as to send a PR? ;-)
