### ISSUE TITLE
Consider generating the "latest and greatest" Excel files from the json from a GitHub actions pipeline

### ISSUE THREAD

**Issue by jelledruyts** [Azure/review-checklists#11]
VBA macros or Office addins are a (slight) burden on users of the Excel, perhaps generating the latest version of the Excel (in multiple languages for different technologies) could simplify "consumption" of the Excel sheet?

**Comment by erjosito** [comment]
Great point @jelledruyts ! I thought about that, but I was not able to find an easy way of generating Excel files with Github actions. Do you have any idea of how to do that?

**Comment by jelledruyts** [comment]
I assume there would be some coding involved :-) Not the end of the world but first of all no point in going this route if the ideal end state isn't excel but some custom web app or Microsoft Assessments or whatever. And perhaps @xstof's no-code idea of using PowerQuery would be even better if you can pull that off!

**Comment by DanielLarsenNZ** [comment]
Happy to have a go at this during FTA Hack week

**Comment by erjosito** [comment]
These Python modules might help: https://www.xlwings.org and https://openpyxl.readthedocs.io

**Comment by erjosito** [comment]
I have started playing with the automatic generation of macro-free .xlsx files, have a look in the `spreadsheet` folder. I am using the Python module `openpyxl`, it does not support all Excel features so I needed to simplify the spreadsheet, but the result is IMHO acceptable.

**Comment by erjosito** [comment]
Related to #13 and #68

**Comment by erjosito** [comment]
This has been implemented for a while now
