### ISSUE TITLE
Statement/Disclaimer around sign-off or endorsement of a landing zone/design document

### ISSUE THREAD

**Issue by ravibak** [Azure/review-checklists#122]
Should we add a statement in welcome page or in disclaimer stating that these spreadsheets/reviews are by no mean a signoff/endorsement of customer/partners landing zone or any other designs ?

**Comment by ravibak** [comment]
Thanks Jose! Will add it

**Comment by erjosito** [comment]
I guess we can close this. Thanks @ravibak !
