### ISSUE TITLE
Status drop box is not available after line item 153 in the checklist. 

### ISSUE THREAD

**Issue by SRINI-THUMALA** [Azure/review-checklists#173]
In the landing zone checklist the Status drop box which has three options (Open, Fulfilled and NA) is not available after the Line item 153 which needs to be fixed.

**Comment by erjosito** [comment]
Thanks @SRINI-THUMALA for opening an issue! We just released v1.1 with a new version of the spreadsheet that should have that fixed, could you please check?
Thanks!

**Comment by SRINI-THUMALA** [comment]
> Thanks @SRINI-THUMALA for opening an issue! We just released v1.1 with a new version of the spreadsheet that should have that fixed, could you please check? Thanks!

Hi Jose (@erjosito ), Thank you for fixing this in short notice. It all looks good now.
