### ISSUE TITLE
Review wording of LZ checklist recommendations

### ISSUE THREAD

**Issue by erjosito** [Azure/review-checklists#182]
Depending on #181 (since we should start with high prio items), we might want to review the wording of the different checks in the LZ checklist, since some of them could be rephrased more clearly.

**Comment by brsteph** [comment]
New guidance should follow: https://github.com/Azure/review-checklists/blob/main/CONTRIBUTING.md#what-to-contribute

**Comment by igorpag** [comment]
Hi @erjosito, since #792 has been merged, do you want to close this item? Regards.
