### ISSUE TITLE
Running ./checklist_graph.sh --technology=lz--format=json results in a number of compliant=undefined results

### ISSUE THREAD

**Issue by hamish-omny** [Azure/review-checklists#203]
I ran `./checklist_graph.sh --technology=lz--format=json` in a azure cloud bash shell, but a number of the results had  `"compliant": "undefined"`. After a quick look it appears a number of the graph queries in lz_checklist.en.json use `Compliant` as the projected column (e.g https://github.com/Azure/review-checklists/blob/main/checklists/lz_checklist.en.json#L135), but `checklist_graph.sh` seems to expect it to be `compliant` https://github.com/Azure/review-checklists/blob/main/scripts/checklist_graph.sh#L256 (note the casing difference).

**Comment by erjosito** [comment]
CC @fskelly 
@hamish-omny I have created PR #226 to fix this
