### ISSUE TITLE
ARG - Add graph query for 'Enforce or appended resource tags through Azure Policy'

### ISSUE THREAD

**Issue by mbrat2005** [Azure/review-checklists#214]
Add an ARG query for the LZ checklist item 'Enforce or appended resource tags through Azure Policy'. 

Write the query to determine whether Policy Assignments exist at the graph query scope for Policies which require or modify resource tags. If assignments exist, return a list of assignment IDs and compliance value '1'

@fskelly 
Still testing this, I'll add it to a PR when completed:
policyresources
    | where type == "microsoft.authorization/policydefinitions"
    | where (properties.policyRule.then.effect in ('append','modify') and properties.policyRule.then matches regex @'tags\[') or (properties.policyRule.then.effect == 'deny' and properties.policyRule.if matches regex @'tags\[')
    | project id
| union (
    policyresources
        | where type == "microsoft.authorization/policydefinitions"
        | where (properties.policyRule.then.effect in ('append','modify') and properties.policyRule.then matches regex @'tags\[') or (properties.policyRule.then.effect == 'deny' and properties.policyRule.if matches regex @'tags\[')
        | project id
        | join kind=innerunique  ( 
            policyresources 
            | where type == "microsoft.authorization/policysetdefinitions" 
            | mv-expand polSetDef = properties.policySetDefinitions
            | extend polSetPolDefId = tostring(polSetDef.policyDefinitionId)
            | project id,polSetPolDefId
        ) on $left.id == $right.polSetPolDefId
    | project id
    )
    | join (policyresources
        | where type == "microsoft.authorization/policyassignments"
        | extend policyDefId = tostring(properties.policyDefinitionId)
        | project policyDefId,assignmentName = name,assignmentScope = properties.scope, assignmentId = id, compliant = 1
        ) on $left.id == $right.policyDefId
| project-away id
| project id = assignmentId,compliant

**Comment by erjosito** [comment]
This is a serious KQL query @mbrat2005 !!

**Comment by fskelly** [comment]
Possible to get a screenshot of the output? Mine is not showing the compliant field - could be my environment. If I then leave the last line in i get an error :( - but I do love the query 👍

Error:
Details:
Query is invalid. Please refer to the documentation for the Azure Resource Graph service and fix the error before retrying. (Code:InvalidQuery)
Regex pattern is ill-formed: tags[ (Code:IllFormedRegexPattern)

Leaving last line out:
I get results - non-compliant to be sure but not the compliant column (for obvious reasons)

**Comment by mbrat2005** [comment]
@fskelly, in testing, the query seems to work well in the ARG Explorer in the Portal (for me!), but not in a PowerShell or Azure CLI terminal. I'll see if I can run down those inconsistencies...

The query as written either returns a list of compliant assignments, or nothing.

**Comment by mbrat2005** [comment]
@fskelly 
See if these version test better. I replaced the 'tags[' regex with 'tags[[]', which seems to make PowerShell happy. I also replaced double quoting with single quoting and confirmed that Azure CLI doesn't like multi-line queries. If you're not getting any results but have tagging policies assigned, double check that the scope of your query should include the assignment. 

**ARG Explorer or PowerShell**
```
policyresources
| where type == 'microsoft.authorization/policydefinitions'
| where (properties.policyRule.then.effect in ('append','modify') and properties.policyRule.then matches regex @'tags[[]') or (properties.policyRule.then.effect == 'deny' and properties.policyRule.if matches regex @'tags[[]')
| project id
| union (
policyresources
| where type == 'microsoft.authorization/policydefinitions'
| where (properties.policyRule.then.effect in ('append','modify') and properties.policyRule.then matches regex @'tags[[]') or (properties.policyRule.then.effect == 'deny' and properties.policyRule.if matches regex @'tags[[]')
| project id
| join kind=innerunique (
policyresources
| where type == 'microsoft.authorization/policysetdefinitions'
| mv-expand polSetDef = properties.policySetDefinitions
| extend polSetPolDefId = tostring(polSetDef.policyDefinitionId)
| project id,polSetPolDefId
) on $left.id == $right.polSetPolDefId
| project id
)
| join (policyresources
| where type == 'microsoft.authorization/policyassignments'
| extend policyDefId = tostring(properties.policyDefinitionId)
| project policyDefId,assignmentName = name,assignmentScope = properties.scope, assignmentId = id, compliant = 1
) on $left.id == $right.policyDefId
| project-away id
| project id = assignmentId,compliant
```
**Azure CLI**
```
policyresources | where type == 'microsoft.authorization/policydefinitions' | where (properties.policyRule.then.effect in ('append','modify') and properties.policyRule.then matches regex @'tags[[]') or (properties.policyRule.then.effect == 'deny' and properties.policyRule.if matches regex @'tags[[]') | project id | union ( policyresources | where type == 'microsoft.authorization/policydefinitions' | where (properties.policyRule.then.effect in ('append','modify') and properties.policyRule.then matches regex @'tags[[]') or (properties.policyRule.then.effect == 'deny' and properties.policyRule.if matches regex @'tags[[]') | project id | join kind=innerunique ( policyresources | where type == 'microsoft.authorization/policysetdefinitions' | mv-expand polSetDef = properties.policySetDefinitions | extend polSetPolDefId = tostring(polSetDef.policyDefinitionId) | project id,polSetPolDefId ) on $left.id == $right.polSetPolDefId | project id ) | join (policyresources | where type == 'microsoft.authorization/policyassignments' | extend policyDefId = tostring(properties.policyDefinitionId) | project policyDefId,assignmentName = name,assignmentScope = properties.scope, assignmentId = id, compliant = 1 ) on $left.id == $right.policyDefId | project-away id | project id = assignmentId,compliant
```
