### ISSUE TITLE
Consider adding a version number to checklists

### ISSUE THREAD

**Issue by mbrat2005** [Azure/review-checklists#234]
Currently, when checklists are shared around, there is no indication of when the checklist content was imported. For example, if an XLSX file is being passed around to bypass client-side restrictions on macros, the spreadsheet may contain outdated content depending on when it was generated. 

Consider adding a version number or "Imported Date" to the pre-generated XLSX files and to the macro import checklist action.

**Comment by erjosito** [comment]
@mbrat2005 This is a very good idea. We recently changed the structure of the Github action doing the automated translation, and now we are finally in a position to automatically add a timestamp to the metadata of the checklists after a push.

**Comment by erjosito** [comment]
Hey @mbrat2005 is the current timestamping of the checklists enough?

**Comment by mbrat2005** [comment]
Yes @erjosito, the import info looks great and should help! I'll close this issue, thanks for addressing it!
