### ISSUE TITLE
How to generate the graph result from Azure

### ISSUE THREAD

**Issue by cheahengsoon** [Azure/review-checklists#239]
Hi Team,
May I ask about to generate the graph result from Azure?
What is the Query needed to Write to match with the review checklist and convert to json?

Thank you

**Comment by sdolgin** [comment]
Hi @cheahengsoon -

Take a look at the readme section on [Using Azure Resource Graph to verify Azure environments (advanced)](https://github.com/Azure/review-checklists#using-azure-resource-graph-to-verify-azure-environments-advanced) if you haven't already.  There is also a shell script which has it's [basic use described here](https://github.com/Azure/review-checklists/blob/main/scripts/README.md).  It has been tested in Cloud Shell successfully.  Does that answer your questions?

**Comment by cheahengsoon** [comment]
Not understand for this --technology=aks , can list all the technology ?

**Comment by sdolgin** [comment]
@cheahengsoon the `--technology` argument specifies the type of technology or checklist to run the graph queries from.
Accepted values are lz, aks and avd and the default is aks. 

lz = landing zone review
aks = AKS review
avd = AVD review

**Comment by cheahengsoon** [comment]
> @cheahengsoon the `--technology` argument specifies the type of technology or checklist to run the graph queries from. Accepted values are lz, aks and avd and the default is aks.
> 
> lz = landing zone review aks = AKS review avd = AVD review

How about security?

**Comment by sdolgin** [comment]
Currently there are no resource graph queries in the security checklist [JSON file](https://github.com/Azure/review-checklists/blob/main/checklists/security_checklist.en.json), so it is moot.  If we get to a point where there are queries contributed for the security recommendations the shell script could be updated to run them as well.

**Comment by cheahengsoon** [comment]
The command not working `./checklist_graph.sh --technology=aks --format=json > ./graph_results.json`
