### ISSUE TITLE
cant work with the script from azure cloud shell

### ISSUE THREAD

**Issue by kinomakino** [Azure/review-checklists#241]
**execution 1**

./checklist_graph.sh --technology=aks --format=json > ./graph_results.json     
ResourceUnavailable: Program 'checklist_graph.sh' failed to run: An error occurred trying to start process '/home/joaquin/checklist_graph.sh' with working directory '/home/joaquin'. No such file or directoryAt line:1 char:1
+ ./checklist_graph.sh --technology=aks --format=json > ./graph_results …
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.

**execution 2**

bash ./checklist_graph.sh --technology=aks --format=json > ./graph_results.json
Usage: file [-bcCdEhikLlNnprsSvzZ0] [--apple] [--extension] [--mime-encoding]
            [--mime-type] [-e <testname>] [-F <separator>]  [-f <namefile>]
            [-m <magicfiles>] [-P <parameter=value>] <file> ...
       file -C [-m <magicfiles>]
       file [--help]
Warning: unknown mime-type for "-r" -- using "application/octet-stream"
Error: no such file "-r

**Comment by sdolgin** [comment]
Hi @kinomakino - It seems you might be trying to execute the Bash script from within the PowerShell environment. If you change the [environment selection](https://docs.microsoft.com/en-us/azure/cloud-shell/overview#choice-of-preferred-shell-experience) in Cloud Shell to Bash it should work.  I have updated the script readme to clarify this.
