### ISSUE TITLE
Download command issue

### ISSUE THREAD

**Issue by CarlH2** [Azure/review-checklists#268]
Hi, I tried to utilise he script provided however it failed with Permission Denied.  As I am not really a Bash user (PowerShell is my thing) it took me some time to realise the issue relates to the provided to download the script and the permissions on the script file were insufficient.  I think the chmod command should probably be chmod +xr rather than chmod +x

wget –quiet –output-document ./checklist_graph.sh https://raw.githubusercontent.com/Azure/review-checklists/main/scripts/checklist_graph.sh chmod +xr ./checklist_graph.sh

**Comment by erjosito** [comment]
Thanks for that @CarlH2 !! I fixed the docs :-)
