### ISSUE TITLE
Dashboard charts have errors for LZ reviews

### ISSUE THREAD

**Issue by AndrewJNorris** [Azure/review-checklists#289]
The dashboard charts have errors for the LZ reviews as the import pulls in a Design Area of 'Application Deployment' that isn't part of an LZ review.
That's creating oddities on the dashboard charts. Example attached.
![image](https://user-images.githubusercontent.com/51118973/209114298-95daba07-1fa8-4210-ad33-68de796f2d6e.png)

**Comment by erjosito** [comment]
Thanks @AndrewJNorris , good catch! I sent this PR to fix it: https://github.com/Azure/review-checklists/pull/291
