### ISSUE TITLE
Conisder removing guidance on creating path based exclusions

### ISSUE THREAD

**Issue by nathanmcnulty** [Azure/review-checklists#325]
Creating path based exclusions introduces unnecessary risk, and we really shouldn't be making this recommendation. Please consider removing this: https://github.com/Azure/review-checklists#unblock-file-or-add-an-exception-to-windows-security

**Comment by erjosito** [comment]
Thanks for this @nathanmcnulty . I will test whether this works, given the fact that in Github repo the files are constantly changing.

**Comment by erjosito** [comment]
Tested and working, docs updated.
