### ISSUE TITLE
Missing "Comment" attribute in the AVD JSON checklist

### ISSUE THREAD

**Issue by igorpag** [Azure/review-checklists#37]
In the original format of AVD XLSX checklist, we populated a column "Comment" with useful information.
There is value in reporting that content, then I would recommend to take back the content from the original XLSZ file and use to add an additional attribute to each JSON fragment.

**Comment by erjosito** [comment]
Hey @igorpag thanks for opening this! My understanding is that the "Comment" column would be used when filling up the spreadsheet when performing the actual review. Is that different with the AVD checklist?

If not, what is the use case here? Saving the progress of a review in JSON format? (the recommended process today would be saving the progress of a review in .xlsx format)

**Comment by igorpag** [comment]
Yes, it is a bit different. We need a field to contain "our" comments to explain more in depth what a "checklist item" is, and provide some more guidance beyond the a simple URL pointing to an article.  A simple title and a URL does not IMO always provide enough to the customer. Let me share with you via mail a sample and a print screen to better explain.

**Comment by erjosito** [comment]
Fixed now, we have added a description column to the spreadsheet
