### ISSUE TITLE
Github actions not allowed to create PRs

### ISSUE THREAD

**Issue by erjosito** [Azure/review-checklists#371]
Started today I noticed that Github actions are not allowed to create PRs any more (see for example https://github.com/Azure/review-checklists/actions/runs/4264274191). The setting to allow actions to create PRs (in https://github.com/Azure/review-checklists/settings/actions) is grayed out, possibly because it is disabled at the Azure organization level.

**Comment by erjosito** [comment]
Related to https://github.com/microsoft/github-operations/issues/222

**Comment by sdolgin** [comment]
PR #373 should be the fix for this.

**Comment by erjosito** [comment]
Yes! Thanks @sdolgin , an automatic translation ran just fine :-)
