### ISSUE TITLE
AVD checklist doc reference link does not work

### ISSUE THREAD

**Issue by dmelgarejoPDESGO** [Azure/review-checklists#386]
link for Check Azure files best practices is broken
https://learn.microsoft.com/azure/architecture/example-scenario/AVD/windows-virtual-desktop-fslogix

**Comment by erjosito** [comment]
@igorpag @bagwyth Could you please have a look at this? Can it be that the right link is https://learn.microsoft.com/azure/virtual-desktop/fslogix-containers-azure-files?

**Comment by bagwyth** [comment]
Curious. The same article is used in multiple places in the checklist but the URL has changed to: https://learn.microsoft.com/azure/architecture/example-scenario/wvd/windows-virtual-desktop-fslogix ("AVD" in the path has changed to "wvd".)

Let me see if I can find out why that URL changed as it was more correct previously (AVD is the correct way to refer to it, WVD is the old name). My concern is that we update the checklist to point to the new location then it gets changed back to AVD again.

**Comment by igorpag** [comment]
Sorry everyone, notification got lost in my inbox. @bagwyth you are referring the right article, let me know if I need to do anything here, for me is ok to change now the URL with the "wvd" label. Thanks.

**Comment by bagwyth** [comment]
Ah. I think I've worked it out: the location of the article hasn't changed. Someone was just a bit enthusiastic doing a replacement of instances of "WVD" with "AVD" in the past. I'll do a PR to fix these links shortly.
