### ISSUE TITLE
checklist_graph script generates 1077 error in Azure shell

### ISSUE THREAD

**Issue by BevanSin** [Azure/review-checklists#416]
when running the script to list the technologies available i get the following output.  This is in an Azure console shell, but its ephemeral - no storage mounted.  Also, I only have read access to all resources.

./checklist_graph.sh --list-technologies

acr_security (0 graph queries)
aks (24 graph queries)
apim (0 graph queries)
appsvc_security (3 graph queries)
asb_security (0 graph queries)
parse error: Invalid numeric literal at line 1077, column 8
avd (0 graph queries)
avs (0 graph queries)
blob_storage_security (0 graph queries)
eh_security (0 graph queries)
lz (20 graph queries)
multitenancy (0 graph queries)
sap (0 graph queries)
security (0 graph queries)
sqldb_security (0 graph queries)

**Comment by erjosito** [comment]
Fixed by #440 

```
jose@Azure:~$ ./checklist_graph.sh -t
acr_security (0 graph queries)
aks (24 graph queries)
apim (0 graph queries)
appsvc_security (3 graph queries)
asb_security (0 graph queries)
avd (0 graph queries)
avs (0 graph queries)
blob_storage_security (0 graph queries)
eh_security (0 graph queries)
lz (30 graph queries)
multitenancy (0 graph queries)
sap (0 graph queries)
security (0 graph queries)
sqldb_security (0 graph queries)
```
