### ISSUE TITLE
Github action not ignoring automatic PRs

### ISSUE THREAD

**Issue by erjosito** [Azure/review-checklists#436]
The flow is the following:
1. User creates a PR
2. Admin merges PR
3. Github action kicks in, and generates a PR with automatic translation (among other things)
4. Admin merges PR
5. Github action kicks in, but recognizes that no translation needs to be done anymore

Step 5 is not working. The part of the action that does that is the following:

```
      # Get list of files that have been changed in the push
      - id: files
        uses: masesgroup/retrieve-changed-files@v2

      # Set variables that indicate whether XLSX files have been modified, which would indicate that
      #   this action has been triggered by an automated action
      - id: automationresult
        name: Verify whether this action is a result of another action
        run: |
          for input_file in ${{ steps.files.outputs.all }}; do
            if [[ "$input_file" == *"xlsx" ]]; then 
              echo "Modification to XLSX file $input_file detected, this seems to be the output of an automated PR"
              echo "excel_file_changed=yes" >> $GITHUB_OUTPUT
            else
              echo "$input_file is not an XLSX file"
            fi
          done
```

If an Excel file has been modified, that means that the merge triggering this action was the result of automatic translation. The rest of the steps have this condition:

```
        if: ${{ steps.automationresult.outputs.excel_file_changed }} != 'yes'
```

However, they still run :-(

**Comment by carlosm00** [comment]
Hi @erjosito ,
I created PR #630 with my suggestion. Please, let me know what you think about it.
Regards.

**Comment by erjosito** [comment]
Thanks @carlosm00 I have been puzzled about this one for a long time! If your proposal fixes this I would gladly invite you to a drink!

**Comment by carlosm00** [comment]
Let's hope for the best @erjosito haha. Also, do you have some test in mind/prepared for this?

**Comment by erjosito** [comment]
Oh, just testing in production :-D An automated PR just went in, and the step where you did your change was skipped, the rest were not. So let me extend the change to the rest of the steps :-)

**Comment by carlosm00** [comment]
Oh, then that sounds good! Thank you @erjosito for allowing me the chance to contribute to this project 😄

**Comment by erjosito** [comment]
Thanks for your contribution @carlosm00 !
