### ISSUE TITLE
latest Checklist could not be downloaded

### ISSUE THREAD

**Issue by KaPaSOne** [Azure/review-checklists#447]
If i use the "import latest checklist" button I get an error that the checklist could not be downloaded. It looks like the file name in the Github Repo has changed.

**Comment by jaffster595** [comment]
I have the exact same issue when trying to download the Landing Zone checklist. I tested a few of the others which appear to be working fine.

**Comment by jaffster595** [comment]
![image](https://github.com/Azure/review-checklists/assets/134733370/4a7f354a-cab4-49b6-931d-2e7d1143a254)

**Comment by KaPaSOne** [comment]
@jaffster595 : You're right. It looks like it's the Landing Zone Checklist only. The name of the File on the Github Directory changed from lz to alz.

**Comment by jaffster595** [comment]
@KaPaSOne Something so simple. I downloaded alz_checklist.en.json, imported it using review_checklist.xlsm and it pulled the list through successfully.

**Comment by erjosito** [comment]
Hey hey! Yes, we changed the name, but the latest version of the .xlsm should be updated to pull the `alz` name.

**Comment by KaPaSOne** [comment]
@jaffster595: Many Thanks for this advice. I had the same idea and tried this one yesterday. I got a failure by importing the predownloaded json file.
@erjosito: it works now. Many thanks for your help.

**Comment by erjosito** [comment]
Sorry for the confusion! The idea was aligning this more to the rest of Microsoft naming convention
