### ISSUE TITLE
Clarification on the rationale behind Governance recommendation.

### ISSUE THREAD

**Issue by BeatrizSilv** [Azure/review-checklists#45]
Under Security Governance and Compliance:
**'Use Azure Policy to control resource provider registrations at the subscription and/or management group levels'**
 
In a recent call with a customer the feedback we got about this guideline was that the rationale behind it wasn't very clear and that it was too specific. Plus, it seems like there is no actual built-in policy to achieve this, so customers would need to create it from scratch.

**Comment by erjosito** [comment]
@alejandra8481 @JasonBeck2 do you know more about that particular recommendation?

**Comment by JasonBeck2** [comment]
I found the recommendation taken from [this security and compliance recommendations page](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/security-governance-and-compliance) and I believe I found more information on it from [this page about creating subscriptions](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/initial-subscriptions). 

_You can allow certain types of Azure resources in your nonproduction subscription for testing purposes. You can enable those resource providers in your nonproduction subscription without making them available in your production environment._

I think we can expand on the existing recommendation to explain this in better detail.

**Comment by BeatrizSilv** [comment]
My 2 cents on this: perhaps we can consider lowering the severity because you can already control what resources/skus cannot be deployed with Azure policy, without having to affect resource provider registrations, so to me at least it sounds a little like overkill. 

Maybe it can be phrased as more of a suggestion (if a customer has a very strict security/cost management posture consider leveraging on Azure policy to control resource provider registrations).

**Comment by JasonBeck2** [comment]
Closing this as the previous changes have been merged.
