### ISSUE TITLE
Access Controls:  Require MFA for Administrators severity

### ISSUE THREAD

**Issue by spaelling** [Azure/review-checklists#465]
the control severity is only `medium` - as this policy protects Global Administrators and other privileged accounts, I have a hard time with this not being a high severity.

check guid is: fe1bd15d-d2f0-4d5e-972d-41e3611cc57b

**Comment by erjosito** [comment]
Hey @brsteph could the ALZ team look into this? Thx!

**Comment by brsteph** [comment]
Hey @erjosito,
 
The GUID: fe1bd15d-d2f0-4d5e-972d-41e3611cc57b is not longer present, the recommendation for enforcing multi-factor has been updated to GUID: 1049d403-a923-4c34-94d0-0018ac6a9e01, with a text of "Enforce multi-factor authentication for any user with rights to the Azure environments" and a severity of "High."  This is showing up both in the code block for the recommendation and in the ALZ macrofree spreadsheet.

Moving forward with new checklists, this should be in line with @spaelling ask.  I believe we can close this.
