### ISSUE TITLE
Configure "Wrap text" in "Checklist item" column

### ISSUE THREAD

**Issue by erjosito** [Azure/review-checklists#47]
Today the elements in the Checklist item column can extend into the next column (Description). The good thing about that is that for the LZ and AKS checklists (which dont have a Description field today), the "Checklist item" text can extend and cover the description cell, which makes it more readable. The downside is that engineers might be confused and fill in the description field instead of the item field.

To prevent that from happening, "Wrap text" could be enabled in the "Checklist item", which would prevent flooding. Any opinion about what would be better from a readability perspective?

**Comment by chboudry** [comment]
Can't we remove the description column in those checklist ? or put it on the far right ? 
Doesn't seem as useul as in the other checklist.

**Comment by erjosito** [comment]
Oops, I missed this one, sorry @chboudry . The feedback of the AVD team is that the description should be next to the checklist text, since those fields go hand in hand.
