### ISSUE TITLE
Help wanted for first steps: How to create new Resource Graph Queries and Workbooks?

### ISSUE THREAD

**Issue by mschwrdtnr** [Azure/review-checklists#492]
Hi people,

thanks for the project! 

I want to participate and create more Resource Graph Queries and maybe more workbooks. I currently don't really know where to start and what makes sense. Can you give me some information about how to start implementing more queries?

**Comment by erjosito** [comment]
@mschwrdtnr thanks for your availability! Creating new queries is relatively easy: there are some simple rules that the queries need to follow, documented in [Adding Resource Graph queries](https://github.com/Azure/review-checklists/blob/main/CONTRIBUTING.md#adding-resource-graph-queries). You can get inspiration from existing queries as well.

Once you have the query, you can add it to the corresponding JSON item, with the `graph` key (have a look at elements with existing queries already).

Once there are enough ARG queries in a checklist, the process of creating the workbook is automatic. We only need to decide which checklist to run it on (today it only runs in the ALZ and AKS checklists), and whether we want workbooks for specific areas of specific checklists (today the only area-specific workbook is for ALZ Networking).

Please let me know if this makes sense, and whether you encounter any challenge contributing.

Thanks!
Jose

**Comment by mschwrdtnr** [comment]
Hi @erjosito, I understand that I just had to read the documentation more deeply. These are enough information for now. Thanks for your clarification!
