### ISSUE TITLE
Update AMMP field in ALZ checklist

### ISSUE THREAD

**Issue by erjosito** [Azure/review-checklists#497]
The AMMP field is now available in the checklists to be used. I put some examples in the ALZ checklists setting the field to `true` for the high-priority items, but the rest of the items (medium and low priority) are not filled in yet.

Would it be possible for the ALZ vTeam to define which of the elements we want to look at in an AMMP review?

Thanks!
jose

**Comment by brsteph** [comment]
We will get this underway!
