### ISSUE TITLE
Scale Nodepool Recommendation under Cost pillar

### ISSUE THREAD

**Issue by kunalchandratre1** [Azure/review-checklists#499]
In AKS, refer to below highlight related to scaling of nodepool snapshot. It is added under the category of cost. Can someone please clarify why and how nodepool snapshot helps on cost optimization in AKS?
![image](https://github.com/Azure/review-checklists/assets/8287325/56890811-aa38-4bb9-80c3-2e6b68b67293)

**Comment by erjosito** [comment]
Thanks for this! Created #524
