### ISSUE TITLE
Kube-advisor deprecated?

### ISSUE THREAD

**Issue by kunalchandratre1** [Azure/review-checklists#500]
One of the recommendations is related to VS Code + Kube Advisor. I see that Kube advisor has been deprectaed as per github link. Can we remove these recommendations or provide alternative?

Develop your YAML manifests with intelligent text editors such as vscode+kubeadvisor.

Deprecation link - https://github.com/Azure/kube-advisor

**Comment by erjosito** [comment]
Thanks for this! Created #524

**Comment by erjosito** [comment]
This one was fixed by #524
