### ISSUE TITLE
ARO checklist - having incorrect reference URL & remove default access

### ISSUE THREAD

**Issue by infosatheesh2020** [Azure/review-checklists#546]
1. I'm referring the ARO checklist item with excel row no. 25 (Whenever possible, remove the service state from inside containers. Instead, use an Azure platform as a service (PaaS) that supports multiregion replication.) which has reference URL for AADDS: 
[More info](https://learn.microsoft.com/azure/active-directory-domain-services/overview)
Please update the right reference.

2. While we advocated to integrate AAD authentication for the ARO console, the default admin access will be still there. There needs to be another checklist item explicitly calling the admin access to be removed. Reference: https://docs.openshift.com/container-platform/4.1/authentication/remove-kubeadmin.html

cc: @msftnadavbh @naioja @erjosito

**Comment by erjosito** [comment]
Good catches @infosatheesh2020 !
