### ISSUE TITLE
Duplicate GUIDs

### ISSUE THREAD

**Issue by lucidqdreams** [Azure/review-checklists#605]
Not sure if this is intentional but there are 4 duplicate GUIDs in 8 records (different checklist files, eg in AVS and AKS json) files. I would expect a GUID to be globally unique.  SAP has one real duplicate in the same file, but the rest don't appear to have anything to do with each other.

Count Name                      Group
----- ----                      -----
    2 143b16c3-1d7a-4a9b-9470-… {@{GUID=143b16c3-1d7a-4a9b-9470-4489a8042d88; File=alz_checklist.en.json}, @{GUID=143b16c3-1d7a-4a9b-9470-4489a8042d88; File=network_appdelivery_checklist.en… 
    2 21d41d25-00b7-407a-b9ea-… {@{GUID=21d41d25-00b7-407a-b9ea-b40fd3290798; File=acr_security_checklist.en.json}, @{GUID=21d41d25-00b7-407a-b9ea-b40fd3290798; File=avs_checklist.en.json}}  
    2 25659d35-58fd-4772-99c9-… {@{GUID=25659d35-58fd-4772-99c9-31112d027fe4; File=avs_checklist.en.json}, @{GUID=25659d35-58fd-4772-99c9-31112d027fe4; File=sql_checklist.en.json}}
    2 43f63047-22d9-429c-8b1c-… {@{GUID=43f63047-22d9-429c-8b1c-d622f54b29ba; File=aks_checklist.en.json}, @{GUID=43f63047-22d9-429c-8b1c-d622f54b29ba; File=avs_checklist.en.json}}
    2 6138a720-0f1c-4e16-bd30-… {@{GUID=6138a720-0f1c-4e16-bd30-1d6e872e52e3; File=alz_checklist.en.json}, @{GUID=6138a720-0f1c-4e16-bd30-1d6e872e52e3; File=network_appdelivery_checklist.en… 
    2 85e2213a-ce7b-4b12-8f7c-… {@{GUID=85e2213a-ce7b-4b12-8f7c-95f06e154e3a; File=sap_checklist.en.json}, @{GUID=85e2213a-ce7b-4b12-8f7c-95f06e154e3a; File=sap_checklist.en.json}}
    2 dbf590ce-65de-48e0-9f9c-… {@{GUID=dbf590ce-65de-48e0-9f9c-cbd468266abc; File=avs_checklist.en.json}, @{GUID=dbf590ce-65de-48e0-9f9c-cbd468266abc; File=sql_checklist.en.json}}
    2 e6a84de5-df43-4d19-a248-… {@{GUID=e6a84de5-df43-4d19-a248-1718d5d1e5f6; File=avs_checklist.en.json}, @{GUID=e6a84de5-df43-4d19-a248-1718d5d1e5f6; File=sql_checklist.en.json}}
    2 fc4972cc-3cd2-45bf-a707-… {@{GUID=fc4972cc-3cd2-45bf-a707-6e9eab4bed32; File=aks_checklist.en.json}, @{GUID=fc4972cc-3cd2-45bf-a707-6e9eab4bed32; File=avd_checklist.en.json}}

Search code

```powershell
$MyChecklistPath = ???

$enJson = Get-ChildItem -Path $MyChecklistPath -Filter *.*en.json | Where-Object {$_.name -ne "lz_checklist.en.json"}
$GUIDList = @()
foreach ($file in $enJson) {
    $Json = Get-Content $file.FullName | ConvertFrom-Json
    $Json.items | ForEach-Object {
        $Duplicates = '' | select GUID, File
        $Duplicates.file = $file.name
        $Duplicates.GUID = $_.guid
        $GUIDList += $Duplicates
    }
}

$duplicateGUIDs = $GUIDList | Group-Object -Property GUID | Where-Object { $_.Count -gt 1 }
```

**Comment by erjosito** [comment]
Good catch @lucidqdreams ! It seems that somebody has been copy/pasting :-) I incorporated your script to the `/scripts` folder of the repo, and fixed most of the duplicates. There is only one left, but since there is currently a PR in flight for the SAP checklist I will wait until that is complete.

Thanks for raising this!

**Comment by erjosito** [comment]
Fixed!
