### ISSUE TITLE
Resource Organization CheckList Item Error

### ISSUE THREAD

**Issue by chrislittle** [Azure/review-checklists#707]
In the Resource Organization > Subscription sub area there is a checklist item titled **"Use Reserved Instances where appropriate to optimize cost and ensure available capacity in target regions. Enforce the use of purchased Reserved Instance VM SKUs via Azure Policy.** 

I believe this must be an error as you don't use Azure Policy to enforce RI purchases. I'm not sure what the intent of the policy statement is meant (2nd sentence) to be as the purchase & application of RI's is based on scope and automatically applied if the scope & resource type align by the billing engine.

**Comment by erjosito** [comment]
Thanks @chrislittle ! @igorjnzl , @brsteph could you have a look? Thanks!

**Comment by igorjnzl** [comment]
I'll review this

**Comment by brsteph** [comment]
#808 has this update.

**Comment by brsteph** [comment]
#808 is merged.
