### ISSUE TITLE
Design - Import button hard to spot

### ISSUE THREAD

**Issue by chboudry** [Azure/review-checklists#72]
![image](https://user-images.githubusercontent.com/51988290/143485649-55106763-7117-451a-8a8f-7c606f1c3a85.png)

I actually had a hard time to see the import button -_-‘
The advanced one’s pop so much to the eyes and because of that the one in the easy box is easy to miss, I would suggest grouping the buttons all together

**Comment by erjosito** [comment]
Is it better now?

**Comment by erjosito** [comment]
Closing as fixed
