### ISSUE TITLE
Duplicate ID (Network Topology and Connectivity)

### ISSUE THREAD

**Issue by chrislittle** [Azure/review-checklists#743]
There appears to be a duplicate checklist ID D06.06 and D01.03.  Both essentially ask the same question.

D01.03:  "Use a DDoS Network or IP protection plans for all Public IP addresses in application landing zones."
D06.06:  "Use Azure DDoS Network or IP Protection plans to help protect Public IP Addresses endpoints within the virtual networks."

Its not entirely clear why these need to be called out separately based on the text framing.  On top of that D01.03 'more info' sends a reviewer to the following URL:  https://learn.microsoft.com/en-us/azure/web-application-firewall/ag/ag-overview which has no discussion about DDoS at all but focused on AppGW WAFs.  I'm wondering if D01.03 is supposed to be focused on WAF not DDoS based on this link, however, later sections (D06:05) already address WAFs.

**Comment by igorjnzl** [comment]
@hgotar1 to review

**Comment by hgotar1** [comment]
I am reviewing this

**Comment by igorjnzl** [comment]
@hgotar1 are you able to review the duplicates here?

**Comment by igorjnzl** [comment]
PR merged & closing as no response
