### ISSUE TITLE
D09.04 - Link to incorrect data

### ISSUE THREAD

**Issue by chrislittle** [Azure/review-checklists#744]
D09.04 has a link to https://learn.microsoft.com/en-us/azure/web-application-firewall/ag/ag-overview when it should link to segmentation details for NSGs

**Comment by igorjnzl** [comment]
@hgotar1 are you able to add this to your PR?

**Comment by hgotar1** [comment]
Yes I am adding this to the next PR

**Comment by igorjnzl** [comment]
PR merged
