### ISSUE TITLE
Translators break JSON structure

### ISSUE THREAD

**Issue by erjosito** [Azure/review-checklists#76]
Translators break JSON structure of the original file. They could be fixed by running this jq query:

cat ./aks_checklist.es.json | jq '. |= . + {"severities": [ .severities[] ] } + {"status": [ .status[] ] } + {"categories": [ .categories[] ] } + {"items": [ .items[] ] }'

**Comment by erjosito** [comment]
This defect could be tracked in #92 , I will leave this open too for the time being

**Comment by sdolgin** [comment]
I've got a fix that uses pwsh in the GH actions workflow to fix the JSON files.  Please review the [update-resource-translator](https://github.com/Azure/review-checklists/tree/update-resource-translator) branch

**Comment by erjosito** [comment]
The `changes` step in the action doesnt seem to be getting the list of the changed files correctly, it looks like the variable `github.event.pull_request.base.sh` is empty at execution time

**Comment by erjosito** [comment]
Fixed by #141!
