### ISSUE TITLE
unable to use checklist_graph

### ISSUE THREAD

**Issue by RackPhilO** [Azure/review-checklists#769]
Followed instructions unable to get script to work using local ubuntu or cloud shell ....

ubuntu@test-ubuntu-cloudinit/checklist/review-checklists/scripts$ ./checklist_graph.sh --list-technologies
-bash: ./checklist_graph.sh: /usr/bin/zsh: bad interpreter: No such file or directory
ubuntu@test-ubuntu-cloudinit:~/checklist/review-checklists/scripts$ bash ./checklist_graph.sh --list-technologies
parse error: Expected string key before ':' at line 1, column 4
checklists/acr_security (0 graph queries)
parse error: Expected string key before ':' at line 1, column 4
checklists/adf (0 graph queries)
parse error: Expected string key before ':' at line 1, column 4

**Comment by anwather** [comment]
Same here

**Comment by erjosito** [comment]
Hey sorry for the delay, somehow this went through the cracks. I think it is fixed now
