### ISSUE TITLE
Deprecation of Security 

### ISSUE THREAD

**Issue by DeanGross** [Azure/review-checklists#831]
How come security has been deprecated? is there a replacement somewhere? [@mgodfrey50](https://github.com/mgodfrey50) [@rudneir2](https://github.com/rudneir2)

**Comment by erjosito** [comment]
This was a request of our security team, since that list hadn't been updated in a while (>1y) and was probably obsolete. Additionally, you find security-related recommendations for most Azure services in the WAF checklist, so it was redundant too.
