### ISSUE TITLE
Macro-enabled Excel file blocked by Windows Security

### ISSUE THREAD

**Issue by erjosito** [Azure/review-checklists#840]
Windows Security might block the download of the macro-enabled file. Here a extract of the extended message:

```
webfile: C:\Users\jomore\Downloads\review_checklist.xlsm|https://objects.githubusercontent.com/github-production-release-asset-2e65be/414928893/fc05dfff-8372-4e71-b141-56304547ab46
?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240808%2Fus-east-1%2Fs3%2Faws4_request
&X-Amz-Date=20240808T121440Z
&X-Amz-Expires=300
&X-Amz-Signature=ac38190f4880daccc51e3774c01a9ca27768d1b80de1c2cf428d8a77237e06a4
&X-Amz-SignedHeaders=host
&actor_id=9462396
&key_id=0
&repo_id=414928893
&response-content-disposition=attachment%3B%20filename%3Dreview_checklist.xlsm&response-content-type=application%2Foctet-stream|pid:20000,ProcessStart:133675928842839019
```

**Comment by erjosito** [comment]
As a workaround, you can go to WIndows Security, Protection Security, and in the event matching the download (probably the last one), in the available actions (bottom right) select "Allow".

**Comment by erjosito** [comment]
After being downloaded, WIndows Security will quarantine the file after a match with the signature `Trojan:Win32/Caynamer.A!ml`. Here again you can go to Windows Security -> Protection Security and select the action "Restore".

**Comment by erjosito** [comment]
The steps above are just a workaround, we should work with the Windows Security team to prevent this false positive.

**Comment by erjosito** [comment]
Today the download is not blocked any more, maybe Windows Security reverted the checkings... Leaving the issue open for a while just in case.

**Comment by DallasHindle** [comment]
On this topic, SentinelOne blocked this file for me in the last 10 minutes due to Malware detection as well.

**Comment by erjosito** [comment]
> On this topic, SentinelOne blocked this file for me in the last 10 minutes due to Malware detection as well.

@DallasHindle do you have any access to SentinelOne to raise a ticket with them?

**Comment by erjosito** [comment]
Closing since no additional incident reported.
