### ISSUE TITLE
Incomplete recommendations

### ISSUE THREAD

**Issue by BeatrizSilv** [Azure/review-checklists#89]
Hello,

The following two recommendations are missing some details:

**Network Topology and Connectivity -> Virtual WAN:**
Recommendation 50 simply says '**Follow the principle**'.

**Network Topology and Connectivity -> Hub and spoke**
Recommendation 56 says '**Consider a network design based on the traditional hub-and-spoke network topology for the following scenarios**', but doesn't actually specify the scenarios.

**Comment by erjosito** [comment]
Good catch Beatriz! I think this might have got lost in the initial copy and paste. Let me have a look...
