### ISSUE TITLE
AKS Checklist clarifications

### ISSUE THREAD

**Issue by infosatheesh2020** [Azure/review-checklists#96]
Recommendation item:

1. If using Azure Disks and AZs, consider dedicating nodes per AZ and WaitForFirstConsumer

The details provided doesn't have adequate clarification on how to dedicate nodes per AZ, and how setting WaitForFirstConsumer will behave (Eg: Will the disk created be pinned in same zone as the VM, and the subsequent pods sharing the PVC scheduled in same zone?) More clarity would be helpful.

2. Make sure no changes are performed by operators in the node RG (aka 'infra RG')

More details on how to achieve this would be helpful. Applying locks doesn't help and it restricts cluster functionality. If any alternates are there, it would be good to document.

3. If not using ephemeral disks, use larger OS disks for the nodes, especially if many pods/node

More details on how would large disk help in multi pods/node scenarios would be helpful.

**Comment by erjosito** [comment]
Hey @infosatheesh2020 thanks for the feedback! The checklist is not supposed to replace Azure Docs, just provide some hints, plus an additional link to Azure Docs where more information is available.

Taking that into account, it would be great if you could send a PR on suggested modifications to the list :-)

Thanks!

**Comment by infosatheesh2020** [comment]
@erjosito Have submitted PR to resolve this issue. Please review.

**Comment by erjosito** [comment]
Hey @infosatheesh2020 thanks a lot for the PR, really appreciate it! I added a few comments to #110  , could you please check? Thanks!

**Comment by infosatheesh2020** [comment]
@erjosito Comments are missing. Did you forgot submitting it?

**Comment by erjosito** [comment]
oops. Now they are in :-)

**Comment by erjosito** [comment]
Including @seenu433 FYI

**Comment by infosatheesh2020** [comment]
@erjosito Updated as per comments. Thanks!
